let data = [
  {
    "id": 777,
    "eid": 777,
    "pid": 0,
    "d_pid": 0,
    "display_name": "Hindi",
    "dn_android": null,
    "dn_desktop": null,
    "dn_mobile": null,
    "icon_url": "footballw.png",
    "weight": 1,
    "in_android": false,
    "in_desktop": true,
    "in_mobile": false,
    "web_type": "link",
    "web_link": "https://hindi.sportscafe.in",
    "desktop_params": {
      "desktop_align": "l"
    },
    "mobile_params": null,
    "droid_type": "sport",
    "droid_params": {
      "sport_id": "football",
      "scores": "true"
    },
    "lang": "en",
    "updatedAt": "2016-08-04T08:42:36.830Z",
    "children": []
  },
  {
    "id": 6,
    "eid": 6,
    "pid": 0,
    "d_pid": 0,
    "display_name": "Cricket",
    "dn_android": null,
    "dn_desktop": null,
    "dn_mobile": null,
    "icon_url": "cricketw.png",
    "weight": 1,
    "in_android": true,
    "in_desktop": true,
    "in_mobile": true,
    "web_type": "link",
    "web_link": "/cricket",
    "desktop_params": {
      "desktop_subcolumns": 4
    },
    "mobile_params": {
      "mobile_collapsed": "n"
    },
    "droid_type": "sport",
    "droid_params": {
      "sport_id": "cricket",
      "scores": "true"
    },
    "lang": "en",
    "updatedAt": "2016-08-04T08:41:34.990Z",
    "children": [
      {
        "id": 33,
        "eid": 33,
        "pid": 6,
        "d_pid": null,
        "display_name": "IND vs NZ",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": null,
        "weight": 1,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/cricket/articles/category/tournament/india_vs_new_zealand",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "tournament",
        "droid_params": {
          "tournament_id": "india_vs_new_zealand",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-09-12T20:33:44.125Z",
        "children": []
      },
      {
        "id": 37,
        "eid": 37,
        "pid": 6,
        "d_pid": null,
        "display_name": "IND PAK Series",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": null,
        "weight": 4,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/cricket/articles/category/tournament/india_pakistan_boycott",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "tournament",
        "droid_params": {
          "tournament_id": "india_pakistan_boycott",
          "scores": "false"
        },
        "lang": "en",
        "updatedAt": "2016-09-12T20:33:44.125Z",
        "children": []
      },
      {
        "id": 36,
        "eid": 36,
        "pid": 6,
        "d_pid": null,
        "display_name": "MS Dhoni",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": null,
        "weight": 5,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/cricket/player/ms_dhoni",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "player",
        "droid_params": {
          "player_id": "ms_dhoni",
          "scores": "false"
        },
        "lang": "en",
        "updatedAt": "2016-09-12T20:33:44.125Z",
        "children": []
      },
      {
        "id": 35,
        "eid": 35,
        "pid": 6,
        "d_pid": null,
        "display_name": "Virat Kohli",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": null,
        "weight": 6,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/cricket/player/virat_kohli",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "player",
        "droid_params": {
          "player_id": "virat_kohli",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-09-12T20:33:44.125Z",
        "children": []
      },
      {
        "id": 38,
        "eid": 38,
        "pid": 6,
        "d_pid": null,
        "display_name": "R Ashwin",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": null,
        "weight": 7,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/cricket/player/ravichandran_ashwin",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "player",
        "droid_params": {
          "player_id": "ravichandran_ashwin",
          "scores": "false"
        },
        "lang": "en",
        "updatedAt": "2016-09-12T20:33:44.125Z",
        "children": []
      },
      {
        "id": 31,
        "eid": 31,
        "pid": 6,
        "d_pid": null,
        "display_name": "Indian Team",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": null,
        "weight": 10,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/cricket/articles/category/team/indian_cricket_team",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "team",
        "droid_params": {
          "team_id": "indian_cricket_team",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-09-12T20:33:44.125Z",
        "children": []
      }
    ],
    "columns": {
      "column0" : [
        {
          "id": 81,
          "eid": 81,
          "pid": 1,
          "display_name": "Home",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 82,
          "eid": 82,
          "pid": 2,
          "display_name": "News",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 83,
          "eid": 83,
          "pid": 3,
          "display_name": "Fixtures",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 84,
          "eid": 84,
          "pid": 3,
          "display_name": "International",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 85,
          "eid": 85,
          "pid": 3,
          "display_name": "National",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        }
      ],
      "column1" : [
        {
          "id": 91,
          "eid": 91,
          "pid": 1,
          "display_name": "Teams",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "icon_url": "sports/football/chennaiyinfc.png",
          "web_type": "text",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 92,
          "eid": 92,
          "pid": 2,
          "display_name": "India",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "icon_url": "sports/football/chennaiyinfc.png",
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 93,
          "eid": 93,
          "pid": 3,
          "display_name": "New Zealand",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "icon_url": "sports/football/chennaiyinfc.png",
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        }
      ],
      "column2" : [
        {
          "id": 91,
          "eid": 91,
          "pid": 1,
          "display_name": "Tournaments",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "icon_url": "sports/football/chennaiyinfc.png",
          "web_type": "text",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 92,
          "eid": 92,
          "pid": 2,
          "display_name": "IPL 2016",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "icon_url": "sports/football/chennaiyinfc.png",
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 93,
          "eid": 93,
          "pid": 3,
          "display_name": "WI vs PAK 2016",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "icon_url": "sports/football/chennaiyinfc.png",
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        }
      ]/*,
       "column3" : [
       {
       "id": 101,
       "eid": 101,
       "pid": 1,
       "display_name": "Players",
       "in_android": false,
       "in_desktop": true,
       "in_mobile": false,
       "web_type": "text",
       "web_link": "/cricket/articles/category/team/indian_cricket_team",
       "desktop_params": true,
       "mobile_params": null,
       "lang": "en",
       "updatedAt": "2016-09-12T20:33:44.125Z",
       "children": []
       },
       {
       "id": 102,
       "eid": 102,
       "pid": 2,
       "display_name": "Taskin Tendulkar",
       "in_android": false,
       "in_desktop": true,
       "in_mobile": false,
       "web_type": "link",
       "web_link": "/cricket/articles/category/team/indian_cricket_team",
       "desktop_params": true,
       "mobile_params": null,
       "lang": "en",
       "updatedAt": "2016-09-12T20:33:44.125Z",
       "children": []
       },
       {
       "id": 103,
       "eid": 103,
       "pid": 3,
       "display_name": "Dravid Warner",
       "in_android": false,
       "in_desktop": true,
       "in_mobile": false,
       "web_type": "link",
       "web_link": "/cricket/articles/category/team/indian_cricket_team",
       "desktop_params": true,
       "mobile_params": null,
       "lang": "en",
       "updatedAt": "2016-09-12T20:33:44.125Z",
       "children": []
       }
       ]*/
    }
  },
  {
    "id": 8,
    "eid": 8,
    "pid": 0,
    "d_pid": 0,
    "display_name": "Football",
    "dn_android": null,
    "dn_desktop": null,
    "dn_mobile": null,
    "icon_url": "footballw.png",
    "weight": 2,
    "in_android": true,
    "in_desktop": true,
    "in_mobile": true,
    "web_type": "link",
    "web_link": "/football",
    "desktop_params": {
      "desktop_subcolumns": 1
    },
    "mobile_params": null,
    "droid_type": "sport",
    "droid_params": {
      "sport_id": "football",
      "scores": "true"
    },
    "lang": "en",
    "updatedAt": "2016-08-04T08:42:36.830Z",
    "children": [
      {
        "id": 81,
        "eid": 81,
        "pid": 8,
        "d_pid": null,
        "display_name": "EPL",
        "dn_android": null,
        "dn_desktop": "EPL",
        "dn_mobile": null,
        "icon_url": "",
        "weight": 1,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/football/articles/category/tournament/english_premier_league",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "tournament",
        "droid_params": {
          "tournament_id": "english_premier_league",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:42:36.830Z",
        "children": []
      },
      {
        "id": 82,
        "eid": 82,
        "pid": 8,
        "d_pid": null,
        "display_name": "La Liga",
        "dn_android": null,
        "dn_desktop": "La Liga",
        "dn_mobile": null,
        "icon_url": "",
        "weight": 1,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/football/articles/category/tournament/la_liga",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "tournament",
        "droid_params": {
          "tournament_id": "la_liga",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:42:36.830Z",
        "children": []
      },
      {
        "id": 84,
        "eid": 84,
        "pid": 8,
        "d_pid": null,
        "display_name": "ISL 2016",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "",
        "weight": 4,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/football/articles/category/tournament/indian_super_league",
        "desktop_params": {
          "desktop_subcolumns": 1
        },
        "mobile_params": null,
        "droid_type": "tournament",
        "droid_params": {
          "tournament_id": "indian_super_league",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:42:36.830Z",
        "children": []
      },
      {
        "id": 85,
        "eid": 85,
        "pid": 8,
        "d_pid": null,
        "display_name": "I-League",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "",
        "weight": 6,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/football/articles/category/tournament/i-league",
        "desktop_params": {
          "desktop_subcolumns": 1
        },
        "mobile_params": null,
        "droid_type": "tournament",
        "droid_params": {
          "tournament_id": "i-league",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:42:36.830Z",
        "children": []
      },
      {
        "id": 88,
        "eid": 88,
        "pid": 8,
        "d_pid": null,
        "display_name": "Cristiano Ronaldo",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "",
        "weight": 8,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/football/player/cristiano_ronaldo",
        "desktop_params": {
          "desktop_subcolumns": 1
        },
        "mobile_params": null,
        "droid_type": "player",
        "droid_params": {
          "player_id": "cristiano_ronaldo",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:42:36.830Z",
        "children": []
      },
      {
        "id": 86,
        "eid": 86,
        "pid": 8,
        "d_pid": null,
        "display_name": "Lionel Messi",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "",
        "weight": 8,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/football/player/lionel_messi",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "player",
        "droid_params": {
          "player_id": "lionel_messi",
          "scores": "false"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:42:36.830Z",
        "children": []
      },
      {
        "id": 83,
        "eid": 83,
        "pid": 8,
        "d_pid": null,
        "display_name": "Fantasy Premier League",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "",
        "weight": 10,
        "in_android": false,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/football/articles/category/tournament/la_liga",
        "desktop_params": {
          "desktop_subcolumns": 1
        },
        "mobile_params": null,
        "droid_type": "sport",
        "droid_params": {
          "sport_id": "football",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:42:36.830Z",
        "children": []
      }
    ]
  },
  {
    "id": 10,
    "eid": 10,
    "pid": 0,
    "d_pid": 0,
    "display_name": "Hockey",
    "dn_android": null,
    "dn_desktop": null,
    "dn_mobile": null,
    "icon_url": "hockeyw.png",
    "weight": 4,
    "in_android": true,
    "in_desktop": true,
    "in_mobile": true,
    "web_type": "link",
    "web_link": "/hockey",
    "desktop_params": {
      "desktop_subcolumns": 1
    },
    "mobile_params": null,
    "droid_type": "sport",
    "droid_params": {
      "sport_id": "hockey",
      "scores": "true"
    },
    "lang": "en",
    "updatedAt": "2016-08-04T08:42:36.830Z",
    "children": [
      {
        "id": 101,
        "eid": 101,
        "pid": 10,
        "d_pid": null,
        "display_name": "India Men's Team",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "",
        "weight": 1,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/hockey/articles/category/team/india_hockey_team",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "team",
        "droid_params": {
          "team_id": "india_hockey_team",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:42:36.830Z",
        "children": []
      },
      {
        "id": 102,
        "eid": 102,
        "pid": 10,
        "d_pid": null,
        "display_name": "India Women's Team",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "",
        "weight": 1,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/hockey/articles/category/team/india_women_hockey_team",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "team",
        "droid_params": {
          "team_id": "india_women_hockey_team",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:42:36.830Z",
        "children": []
      },
      {
        "id": 103,
        "eid": 103,
        "pid": 10,
        "d_pid": null,
        "display_name": "PR Sreejesh",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "",
        "weight": 3,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/hockey/player/pr_sreejesh",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "player",
        "droid_params": {
          "player_id": "hockey",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:42:36.830Z",
        "children": []
      },
      {
        "id": 104,
        "eid": 104,
        "pid": 10,
        "d_pid": null,
        "display_name": "Sushila Chanu",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "",
        "weight": 3,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/hockey/player/sushila_chanu",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "player",
        "droid_params": {
          "player_id": "sushila_chanu",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:42:36.830Z",
        "children": []
      }
    ]
  },
  {
    "id": 11,
    "eid": 11,
    "pid": 0,
    "d_pid": 0,
    "display_name": "Kabaddi",
    "dn_android": null,
    "dn_desktop": null,
    "dn_mobile": null,
    "icon_url": "kabaddiw.png",
    "weight": 12,
    "in_android": true,
    "in_desktop": true,
    "in_mobile": true,
    "web_type": "link",
    "web_link": "/kabaddi",
    "desktop_params": {
      "desktop_subcolumns": 4,
      "desktop_subcol_align": "l"
    },
    "mobile_params": null,
    "droid_type": "sport",
    "droid_params": {
      "sport_id": "kabaddi",
      "scores": "true"
    },
    "lang": "en",
    "updatedAt": "2016-08-06T04:20:26.538Z",
    "children": [
      {
        "id": 912,
        "eid": 912,
        "pid": 11,
        "d_pid": null,
        "display_name": "IND vs IRA WC Final",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "kabaddiw.png",
        "weight": 1,
        "in_android": false,
        "in_desktop": true,
        "in_mobile": false,
        "web_type": "link",
        "web_link": "/matchcentre/kabaddi/kabaddiworldcup2016/33",
        "desktop_params": {
          "desktop_subcolumns": "l"
        },
        "mobile_params": {
          "mobile_collapsed": "y"
        },
        "droid_type": "sport",
        "droid_params": {
          "sport_id": "tennis",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:42:45.440Z",
        "children": []
      },
      {
        "id": 112,
        "eid": 112,
        "pid": 11,
        "d_pid": null,
        "display_name": "Kabaddi World Cup",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": null,
        "weight": 2,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/kabaddi/articles/category/tournament/kabaddi_world_cup",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "tournament",
        "droid_params": {
          "tournament_id": "pro_kabaddi_league_2016",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-09-12T20:33:44.125Z",
        "children": []
      },
      {
        "id": 114,
        "eid": 114,
        "pid": 11,
        "d_pid": null,
        "display_name": "Rahul Chaudhari",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": null,
        "weight": 3,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/kabaddi/player/rahul_chaudhari",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "player",
        "droid_params": {
          "player_id": "rahul_chaudhari",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-09-12T20:33:44.125Z",
        "children": []
      },
      {
        "id": 115,
        "eid": 115,
        "pid": 11,
        "d_pid": null,
        "display_name": "Anup Kumar",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": null,
        "weight": 4,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/kabaddi/player/anup_kumar",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "player",
        "droid_params": {
          "player_id": "anup_kumar",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-09-12T20:33:44.125Z",
        "children": []
      },
      {
        "id": 113,
        "eid": 113,
        "pid": 11,
        "d_pid": null,
        "display_name": "Manjeet Chhillar",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": null,
        "weight": 4,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/kabaddi/player/manjeet_chhillar",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "player",
        "droid_params": {
          "player_id": "manjeet_chhillar",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-09-12T20:33:44.125Z",
        "children": []
      }
    ],
    "columns": {
      "column0" : [
        {
          "id": 81,
          "eid": 81,
          "pid": 1,
          "display_name": "Home",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 82,
          "eid": 82,
          "pid": 2,
          "display_name": "News",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 83,
          "eid": 83,
          "pid": 3,
          "display_name": "Fixtures",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 84,
          "eid": 84,
          "pid": 3,
          "display_name": "International",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 85,
          "eid": 85,
          "pid": 3,
          "display_name": "National",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        }
      ],
      "column1" : [
        {
          "id": 91,
          "eid": 91,
          "pid": 1,
          "display_name": "Teams",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "icon_url": "sports/football/chennaiyinfc.png",
          "web_type": "text",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 92,
          "eid": 92,
          "pid": 2,
          "display_name": "India",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "icon_url": "sports/football/chennaiyinfc.png",
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 93,
          "eid": 93,
          "pid": 3,
          "display_name": "New Zealand",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "icon_url": "sports/football/chennaiyinfc.png",
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        }
      ],
      "column2" : [
        {
          "id": 91,
          "eid": 91,
          "pid": 1,
          "display_name": "Tournaments",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "icon_url": "sports/football/chennaiyinfc.png",
          "web_type": "text",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 92,
          "eid": 92,
          "pid": 2,
          "display_name": "IPL 2016",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "icon_url": "sports/football/chennaiyinfc.png",
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 93,
          "eid": 93,
          "pid": 3,
          "display_name": "WI vs PAK 2016",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "icon_url": "sports/football/chennaiyinfc.png",
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        }
      ],
      "column3" : [
        {
          "id": 101,
          "eid": 101,
          "pid": 1,
          "display_name": "Players",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "web_type": "text",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 102,
          "eid": 102,
          "pid": 2,
          "display_name": "Taskin Tendulkar",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        },
        {
          "id": 103,
          "eid": 103,
          "pid": 3,
          "display_name": "Dravid Warner",
          "in_android": false,
          "in_desktop": true,
          "in_mobile": false,
          "web_type": "link",
          "web_link": "/cricket/articles/category/team/indian_cricket_team",
          "desktop_params": true,
          "mobile_params": null,
          "lang": "en",
          "updatedAt": "2016-09-12T20:33:44.125Z",
          "children": []
        }
      ]
    }
  },
  {
    "id": 2,
    "eid": 2,
    "pid": 0,
    "d_pid": null,
    "display_name": "Sports",
    "dn_android": null,
    "dn_desktop": "Sports",
    "dn_mobile": null,
    "icon_url": "othersportsw.png",
    "weight": 37,
    "in_android": true,
    "in_desktop": true,
    "in_mobile": true,
    "web_type": "text",
    "web_link": null,
    "desktop_params": {
      "desktop_align": "l",
      "desktop_subcolumns": 2
    },
    "mobile_params": {
      "mobile_align": "t",
      "mobile_collapsed": "y"
    },
    "droid_type": "category",
    "droid_params": null,
    "lang": "en",
    "updatedAt": "2016-07-02T10:06:49.360Z",
    "children": [
      {
        "id": 32,
        "eid": 32,
        "pid": 2,
        "d_pid": null,
        "display_name": "India Cricket Team",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "cricketw.png",
        "weight": 2,
        "in_android": false,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/cricket/articles/category/team/india_cricket_team",
        "desktop_params": null,
        "mobile_params": null,
        "droid_type": "sports",
        "droid_params": {
          "sport_id": "cricket",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-09-12T20:33:44.125Z",
        "children": []
      },
      {
        "id": 7,
        "eid": 7,
        "pid": 2,
        "d_pid": null,
        "display_name": "Tennis",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "tennisw.png",
        "weight": 2,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/tennis",
        "desktop_params": {
          "desktop_subcol_align": "l"
        },
        "mobile_params": {
          "mobile_collapsed": "y"
        },
        "droid_type": "sport",
        "droid_params": {
          "sport_id": "tennis",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:42:45.440Z",
        "children": [
          {
            "id": 71,
            "eid": 71,
            "pid": 7,
            "d_pid": null,
            "display_name": "US Open",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/tennis/articles/category/tournament/us_open_2016",
            "desktop_params": {
              "desktop_subcolumns": 1
            },
            "mobile_params": {
              "mobile_collapsed": "y"
            },
            "droid_type": "tournament",
            "droid_params": {
              "tournament_id": "us_open_2016",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:42:45.440Z",
            "children": []
          },
          {
            "id": 72,
            "eid": 72,
            "pid": 7,
            "d_pid": null,
            "display_name": "Novak Djokovic",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 2,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/tennis/player/novak_djokovic",
            "desktop_params": {
              "desktop_subcolumns": 1
            },
            "mobile_params": {
              "mobile_collapsed": "y"
            },
            "droid_type": "player",
            "droid_params": {
              "player_id": "novak_djokovic",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:42:45.440Z",
            "children": []
          },
          {
            "id": 73,
            "eid": 73,
            "pid": 7,
            "d_pid": null,
            "display_name": "Sania Mirza",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 2,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/tennis/player/sania_mirza",
            "desktop_params": {
              "desktop_subcolumns": 1
            },
            "mobile_params": {
              "mobile_collapsed": "y"
            },
            "droid_type": "player",
            "droid_params": {
              "player_id": "sania_mirza",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:42:45.440Z",
            "children": []
          },
          {
            "id": 78,
            "eid": 78,
            "pid": 7,
            "d_pid": null,
            "display_name": "Rohan Bopanna",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 3,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/tennis/player/rohan_bopanna",
            "desktop_params": {
              "desktop_subcolumns": 1
            },
            "mobile_params": {
              "mobile_collapsed": "y"
            },
            "droid_type": "player",
            "droid_params": {
              "player_id": "rohan_bopanna",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:42:45.440Z",
            "children": []
          },
          {
            "id": 74,
            "eid": 74,
            "pid": 7,
            "d_pid": null,
            "display_name": "Roger Federer",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 4,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/tennis/player/roger_federer",
            "desktop_params": {
              "desktop_subcolumns": 1
            },
            "mobile_params": {
              "mobile_collapsed": "y"
            },
            "droid_type": "player",
            "droid_params": {
              "player_id": "roger_federer",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:42:45.440Z",
            "children": []
          },
          {
            "id": 75,
            "eid": 75,
            "pid": 7,
            "d_pid": null,
            "display_name": "Rafael Nadal",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 4,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/tennis/player/rafael_nadal",
            "desktop_params": null,
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "rafael_nadal",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:42:45.440Z",
            "children": []
          },
          {
            "id": 77,
            "eid": 77,
            "pid": 7,
            "d_pid": null,
            "display_name": "Andy Murray",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 7,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/tennis/player/andy_murray",
            "desktop_params": {
              "desktop_subcolumns": 1
            },
            "mobile_params": {
              "mobile_collapsed": "y"
            },
            "droid_type": "player",
            "droid_params": {
              "player_id": "andy_murray",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:42:45.440Z",
            "children": []
          }
        ]
      },
      {
        "id": 60,
        "eid": 60,
        "pid": 2,
        "d_pid": null,
        "display_name": "Squash",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "squashw.png",
        "weight": 10,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/squash",
        "desktop_params": {
          "desktop_subcol_align": "r"
        },
        "mobile_params": null,
        "droid_type": "sport",
        "droid_params": {
          "sport_id": "squash",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:41:47.570Z",
        "children": [
          {
            "id": 161,
            "eid": 161,
            "pid": 60,
            "d_pid": null,
            "display_name": "Dipika Pallikal",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": null,
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/squash/player/dipika_pallikal",
            "desktop_params": {
              "desktop_subcol_align": "l"
            },
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "dipika_pallikal",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:41:47.570Z",
            "children": []
          },
          {
            "id": 162,
            "eid": 162,
            "pid": 60,
            "d_pid": null,
            "display_name": "Joshna Chinappa",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 2,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/squash/player/joshna_chinappa",
            "desktop_params": {
              "desktop_subcol_align": "l"
            },
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "joshna_chinappa",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:41:47.570Z",
            "children": []
          }
        ]
      },
      {
        "id": 9,
        "eid": 9,
        "pid": 2,
        "d_pid": null,
        "display_name": "Badminton",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "badmintonw.png",
        "weight": 11,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/badminton",
        "desktop_params": {
          "desktop_subcol_align": "l"
        },
        "mobile_params": null,
        "droid_type": "sport",
        "droid_params": {
          "sport_id": "badminton",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:41:47.570Z",
        "children": [
          {
            "id": 95,
            "eid": 95,
            "pid": 9,
            "d_pid": null,
            "display_name": "P Gopichand",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 2,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/badminton/player/pullela_gopichand",
            "desktop_params": null,
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "pullela_gopichand",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:41:47.570Z",
            "children": []
          },
          {
            "id": 92,
            "eid": 92,
            "pid": 9,
            "d_pid": null,
            "display_name": "Saina Nehwal",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 2,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/badminton/player/saina_nehwal",
            "desktop_params": null,
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "saina_nehwal",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:41:47.570Z",
            "children": []
          },
          {
            "id": 91,
            "eid": 91,
            "pid": 9,
            "d_pid": null,
            "display_name": "PV Sindhu",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 4,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/badminton/player/pv_sindhu",
            "desktop_params": null,
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "pv_sindhu",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:41:47.570Z",
            "children": []
          },
          {
            "id": 93,
            "eid": 93,
            "pid": 9,
            "d_pid": null,
            "display_name": "Kidambi Srikanth",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 5,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/badminton/player/kidambi_srikanth",
            "desktop_params": null,
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "kidambi_srikanth",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:41:47.570Z",
            "children": []
          }
        ]
      },
      {
        "id": 1080,
        "eid": 1080,
        "pid": 2,
        "d_pid": null,
        "display_name": "Campus",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "athleticsw.png",
        "weight": 12,
        "in_android": false,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/campus",
        "desktop_params": {
          "desktop_subcol_align": "r"
        },
        "mobile_params": null,
        "droid_type": "sport",
        "droid_params": {
          "sport_id": "chess",
          "scores": "false"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:41:47.570Z",
        "children": []
      },
      {
        "id": 180,
        "eid": 180,
        "pid": 2,
        "d_pid": null,
        "display_name": "Chess",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "chessw.png",
        "weight": 12,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/chess",
        "desktop_params": {
          "desktop_subcol_align": "r"
        },
        "mobile_params": null,
        "droid_type": "sport",
        "droid_params": {
          "sport_id": "chess",
          "scores": "false"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:41:47.570Z",
        "children": [
          {
            "id": 1180,
            "eid": 1180,
            "pid": 180,
            "d_pid": null,
            "display_name": "Viswanathan Anand",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/chess/player/viswanathan_anand",
            "desktop_params": {
              "desktop_subcol_align": "l"
            },
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "viswanathan_anand",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:41:47.570Z",
            "children": []
          }
        ]
      },
      {
        "id": 130,
        "eid": 130,
        "pid": 2,
        "d_pid": null,
        "display_name": "Wrestling",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "wrestlingw.png",
        "weight": 13,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/wrestling",
        "desktop_params": {
          "desktop_subcol_align": "r"
        },
        "mobile_params": null,
        "droid_type": "sport",
        "droid_params": {
          "sport_id": "wrestling",
          "scores": "false"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:41:47.570Z",
        "children": [
          {
            "id": 135,
            "eid": 135,
            "pid": 130,
            "d_pid": null,
            "display_name": "Yogeshwar Dutt",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": null,
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/wrestling/player/yogeshwar_dutt",
            "desktop_params": null,
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "yogeshwar_dutt",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-09-12T20:33:44.125Z",
            "children": []
          },
          {
            "id": 133,
            "eid": 133,
            "pid": 130,
            "d_pid": null,
            "display_name": "Sushil Kumar",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": null,
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/wrestling/player/sushil_kumar",
            "desktop_params": null,
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "sushil_kumar",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-09-12T20:33:44.125Z",
            "children": []
          },
          {
            "id": 132,
            "eid": 132,
            "pid": 130,
            "d_pid": null,
            "display_name": "Narsingh Yadav",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": null,
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/wrestling/player/narsingh_yadav",
            "desktop_params": null,
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "narsingh_yadav",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-09-12T20:33:44.125Z",
            "children": []
          },
          {
            "id": 131,
            "eid": 131,
            "pid": 130,
            "d_pid": null,
            "display_name": "Sakshi Malik",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": null,
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/wrestling/player/sakshi_malik",
            "desktop_params": null,
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "sakshi_malik",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-09-12T20:33:44.125Z",
            "children": []
          }
        ]
      },
      {
        "id": 120,
        "eid": 120,
        "pid": 2,
        "d_pid": null,
        "display_name": "Boxing",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "boxingw.png",
        "weight": 13,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/boxing",
        "desktop_params": {
          "desktop_subcol_align": "r"
        },
        "mobile_params": null,
        "droid_type": "sport",
        "droid_params": {
          "sport_id": "boxing",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:41:47.570Z",
        "children": [
          {
            "id": 123,
            "eid": 123,
            "pid": 120,
            "d_pid": null,
            "display_name": "Mary Kom",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": null,
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/boxing/player/mary_kom",
            "desktop_params": null,
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "mary_kom",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-09-12T20:33:44.125Z",
            "children": []
          },
          {
            "id": 121,
            "eid": 121,
            "pid": 120,
            "d_pid": null,
            "display_name": "Vijender Singh",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": null,
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/boxing/player/vijender_singh",
            "desktop_params": null,
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "vijender_singh",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-09-12T20:33:44.125Z",
            "children": []
          },
          {
            "id": 122,
            "eid": 122,
            "pid": 120,
            "d_pid": null,
            "display_name": "Shiva Thapa",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": null,
            "weight": 4,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/boxing/player/shiva_thapa",
            "desktop_params": null,
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "shiva_thapa",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-09-12T20:33:44.125Z",
            "children": []
          }
        ]
      },
      {
        "id": 170,
        "eid": 170,
        "pid": 2,
        "d_pid": null,
        "display_name": "Shooting",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "shootingw.png",
        "weight": 14,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/shooting",
        "desktop_params": {
          "desktop_subcol_align": "l"
        },
        "mobile_params": null,
        "droid_type": "sport",
        "droid_params": {
          "sport_id": "shooting",
          "scores": "false"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:41:47.570Z",
        "children": [
          {
            "id": 173,
            "eid": 173,
            "pid": 170,
            "d_pid": null,
            "display_name": "Abhinav Bindra",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/shooting/player/abhinav_bindra",
            "desktop_params": null,
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "abhinav_bindra",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:41:47.570Z",
            "children": []
          },
          {
            "id": 172,
            "eid": 172,
            "pid": 170,
            "d_pid": null,
            "display_name": "Jitu Rai",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/shooting/player/jitu_rai",
            "desktop_params": null,
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "jitu_rai",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:41:47.570Z",
            "children": []
          },
          {
            "id": 171,
            "eid": 171,
            "pid": 170,
            "d_pid": null,
            "display_name": "Gagan Narang",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/shooting/player/gagan_narang",
            "desktop_params": null,
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "gagan_narang",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:41:47.570Z",
            "children": []
          }
        ]
      },
      {
        "id": 200,
        "eid": 200,
        "pid": 2,
        "d_pid": null,
        "display_name": "Cue Sports",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "cuew.png",
        "weight": 15,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/cuesports",
        "desktop_params": {
          "desktop_subcol_align": "r"
        },
        "mobile_params": null,
        "droid_type": "sport",
        "droid_params": {
          "sport_id": "cuesports",
          "scores": "false"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:41:47.570Z",
        "children": [
          {
            "id": 201,
            "eid": 201,
            "pid": 200,
            "d_pid": null,
            "display_name": "Pankaj Advani",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/cuesports/player/pankaj_advani",
            "desktop_params": {
              "desktop_subcol_align": "l"
            },
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "pankaj_advani",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:41:47.570Z",
            "children": []
          }
        ]
      },
      {
        "id": 140,
        "eid": 140,
        "pid": 2,
        "d_pid": null,
        "display_name": "Archery",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "archeryw.png",
        "weight": 15,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/archery",
        "desktop_params": {
          "desktop_subcol_align": "r"
        },
        "mobile_params": null,
        "droid_type": "sport",
        "droid_params": {
          "sport_id": "archery",
          "scores": "false"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:41:47.570Z",
        "children": [
          {
            "id": 146,
            "eid": 147,
            "pid": 140,
            "d_pid": null,
            "display_name": "Atanu Das",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/archery/player/atanu_das",
            "desktop_params": {
              "desktop_subcol_align": "l"
            },
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "atanu_das",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:41:47.570Z",
            "children": []
          },
          {
            "id": 145,
            "eid": 145,
            "pid": 140,
            "d_pid": null,
            "display_name": "Deepika Kumari",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/archery/player/deepika_kumari",
            "desktop_params": {
              "desktop_subcol_align": "l"
            },
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "deepika_kumari",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:41:47.570Z",
            "children": []
          },
          {
            "id": 141,
            "eid": 141,
            "pid": 140,
            "d_pid": null,
            "display_name": "National",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 12,
            "in_android": false,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/archery/national",
            "desktop_params": {
              "desktop_subcol_align": "r"
            },
            "mobile_params": null,
            "droid_type": "sport",
            "droid_params": {
              "sport_id": "archery",
              "scores": "false"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:41:47.570Z",
            "children": []
          }
        ]
      },
      {
        "id": 160,
        "eid": 160,
        "pid": 2,
        "d_pid": null,
        "display_name": "Athletics",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "athleticsw.png",
        "weight": 16,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/athletics",
        "desktop_params": {
          "desktop_subcol_align": "l"
        },
        "mobile_params": null,
        "droid_type": "sport",
        "droid_params": {
          "sport_id": "athletics",
          "scores": "false"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:41:47.570Z",
        "children": [
          {
            "id": 1611,
            "eid": 1611,
            "pid": 160,
            "d_pid": null,
            "display_name": "Dutee Chand",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/athletics/player/dutee_chand",
            "desktop_params": {
              "desktop_subcol_align": "l"
            },
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "dutee_chand",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:41:47.570Z",
            "children": []
          },
          {
            "id": 1612,
            "eid": 1612,
            "pid": 160,
            "d_pid": null,
            "display_name": "OP Jaisha",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/athletics/player/op_jaisha",
            "desktop_params": {
              "desktop_subcol_align": "l"
            },
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "op_jaisha",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:41:47.570Z",
            "children": []
          }
        ]
      },
      {
        "id": 21,
        "eid": 21,
        "pid": 2,
        "d_pid": null,
        "display_name": "Across Sports",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "othersportsw.png",
        "weight": 22,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/othersports",
        "desktop_params": {
          "desktop_subcol_align": "l"
        },
        "mobile_params": null,
        "droid_type": "sport",
        "droid_params": {
          "sport_id": "othersports",
          "scores": "false"
        },
        "lang": "en",
        "updatedAt": "2016-08-23T13:57:00.550Z",
        "children": [
          {
            "id": 211,
            "eid": 211,
            "pid": 21,
            "d_pid": null,
            "display_name": "Dipa Karmakar",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/othersports/player/dipa_karmakar",
            "desktop_params": {
              "desktop_subcol_align": "l"
            },
            "mobile_params": null,
            "droid_type": "player",
            "droid_params": {
              "player_id": "dipa_karmakar",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:41:47.570Z",
            "children": []
          }
        ]
      },
      {
        "id": 15,
        "eid": 15,
        "pid": 2,
        "d_pid": null,
        "display_name": "Rio Olympics",
        "dn_android": null,
        "dn_desktop": null,
        "dn_mobile": null,
        "icon_url": "olympicw.png",
        "weight": 30,
        "in_android": true,
        "in_desktop": true,
        "in_mobile": true,
        "web_type": "link",
        "web_link": "/rio-olympics-2016",
        "desktop_params": {
          "desktop_subcolumns": 1
        },
        "mobile_params": {
          "mobile_collapsed": "y"
        },
        "droid_type": "sport",
        "droid_params": {
          "sport_id": "tennis",
          "scores": "true"
        },
        "lang": "en",
        "updatedAt": "2016-08-04T08:42:45.440Z",
        "children": [
          {
            "id": 152,
            "eid": 152,
            "pid": 15,
            "d_pid": null,
            "display_name": "Rio '16 News",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 1,
            "in_android": true,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/sports/articles/category/tournament/rio_2016",
            "desktop_params": {
              "desktop_subcolumns": 1
            },
            "mobile_params": {
              "mobile_collapsed": "y"
            },
            "droid_type": "sport",
            "droid_params": {
              "sport_id": "tennis",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:42:45.440Z",
            "children": []
          },
          {
            "id": 153,
            "eid": 153,
            "pid": 15,
            "d_pid": null,
            "display_name": "Paralympics 2016",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 1,
            "in_android": false,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/sports/articles/category/tournament/paralympics_2016",
            "desktop_params": {
              "desktop_subcolumns": 1
            },
            "mobile_params": {
              "mobile_collapsed": "y"
            },
            "droid_type": "sport",
            "droid_params": {
              "sport_id": "tennis",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:42:45.440Z",
            "children": []
          },
          {
            "id": 151,
            "eid": 151,
            "pid": 15,
            "d_pid": null,
            "display_name": "Rio '16 Live Blog",
            "dn_android": null,
            "dn_desktop": null,
            "dn_mobile": null,
            "icon_url": "",
            "weight": 1,
            "in_android": false,
            "in_desktop": true,
            "in_mobile": true,
            "web_type": "link",
            "web_link": "/rio-olympics-2016",
            "desktop_params": {
              "desktop_subcolumns": 1
            },
            "mobile_params": {
              "mobile_collapsed": "y"
            },
            "droid_type": "sport",
            "droid_params": {
              "sport_id": "tennis",
              "scores": "true"
            },
            "lang": "en",
            "updatedAt": "2016-08-04T08:42:45.440Z",
            "children": []
          }
        ]
      }
    ]
  }
];

export default data;